# Generated by Django 2.0.6 on 2018-10-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('yearReleased', models.IntegerField(max_length=5)),
                ('rating', models.CharField(max_length=1)),
                ('genre', models.CharField(max_length=200)),
                ('summary', models.TextField(max_length=500)),
            ],
        ),
    ]
